# B站房间号
room_id: 23197314
# cookies保存文件名称
cookies: cookies.txt
# 检测时长t
check_length: 30
# 最小弹幕频率f
min_freq: 1
# 发送间隔
# 此项为一个键值对，左边表示弹幕频率，右边表示间隔
# 例如：发送频率1-1.5时，间隔18s
# 发送频率1.5-2.0时，间隔15s
# 发送频率2.0-2.5时，间隔12.5s
# 另外，此项也可以为一个纯数字，表示不使用动态发送间隔
interval: 
  1: 18
  1.5: 15
  2.0: 12.5
  2.5: 10
  3: 8
# 挑选的弹幕个数n
random_size: 3
# 过滤没有粉丝牌的弹幕
# medal表示带牌子就行，fans表示必须是当前主播的粉丝牌，none表示不过滤
filter_medal: medal
# 过滤自己发送的弹幕，默认true
filter_self: true